// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Run with `pnpm db:seed` (also used by `prisma migrate reset`).
    seed: "tsx prisma/seed.ts",
  },
  // Read lazily instead of via `env()` so `prisma generate` (postinstall) works
  // before a .env exists. The app itself validates env vars in src/lib/env.ts.
  datasource: {
    url: process.env.DATABASE_URL,
  },
});