import fs from 'node:fs';
import path from 'node:path';

const BUILD_DIR = './build';

if (!fs.existsSync(BUILD_DIR)) {
  fs.mkdirSync(BUILD_DIR, { recursive: true });
}

const themes = ['wire-desk', 'visual-led', 'measured-editorial'];
const modes = ['light', 'dark'];

function loadJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

function deepMerge(target, source) {
  const result = {};
  const allKeys = new Set([...Object.keys(target || {}), ...Object.keys(source || {})]);
  for (const key of allKeys) {
    const t = target?.[key];
    const s = source?.[key];
    if (s === undefined) {
      result[key] = t;
    } else if (t === undefined) {
      result[key] = s;
    } else if (
      typeof t === 'object' && t !== null && !t.$value &&
      typeof s === 'object' && s !== null && !s.$value
    ) {
      result[key] = deepMerge(t, s);
    } else {
      result[key] = s;
    }
  }
  return result;
}

function resolveTokenValue(value, tokenTree) {
  if (typeof value !== 'string') return value;
  const match = value.match(/^\{(.+)\}$/);
  if (!match) return value;
  const refPath = match[1];
  const parts = refPath.split('.');
  let current = tokenTree;
  for (const part of parts) {
    current = current?.[part];
    if (current === undefined) return value;
  }
  if (current && typeof current === 'object' && current.$value) {
    return resolveTokenValue(current.$value, tokenTree);
  }
  if (typeof current === 'string') {
    return resolveTokenValue(current, tokenTree);
  }
  return value;
}

function resolveAllTokens(obj, tokenTree, prefix = '') {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    const newKey = prefix ? `${prefix}-${key}` : key;
    if (value && typeof value === 'object' && value.$value) {
      result[newKey] = resolveTokenValue(value.$value, tokenTree);
    } else if (value && typeof value === 'object' && !value.$value) {
      Object.assign(result, resolveAllTokens(value, tokenTree, newKey));
    }
  }
  return result;
}

function loadAllPrimitives() {
  const primDir = './src/primitives';
  let merged = {};
  for (const file of fs.readdirSync(primDir)) {
    if (file.endsWith('.json')) {
      merged = deepMerge(merged, loadJson(path.join(primDir, file)));
    }
  }
  return merged;
}

function buildResolved(theme, mode) {
  const primitives = loadAllPrimitives();
  const semFile = mode === 'dark' ? './src/semantic/dark.json' : './src/semantic/light.json';
  const semantic = loadJson(semFile);
  const themeFile = `./src/themes/${theme}.json`;
  let themeOverrides = {};
  if (fs.existsSync(themeFile)) {
    const raw = loadJson(themeFile);
    if (raw.color !== undefined) {
      throw new Error(
        `${themeFile}: found top-level "color" overrides. Scope them under "light" or "dark" so a per-theme override can't clobber the opposite mode's base values.`
      );
    }
    const { light, dark, ...shared } = raw;
    const modeScoped = mode === 'dark' ? (dark ?? {}) : (light ?? {});
    themeOverrides = deepMerge(shared, modeScoped);
  }

  const merged = deepMerge(deepMerge(primitives, semantic), themeOverrides);
  const fullTree = deepMerge(primitives, merged);

  const compDir = './src/component';
  let allComponentTokens = {};
  if (fs.existsSync(compDir)) {
    for (const file of fs.readdirSync(compDir)) {
      if (file.endsWith('.json')) {
        const compTokens = loadJson(path.join(compDir, file));
        allComponentTokens = deepMerge(allComponentTokens, compTokens);
      }
    }
  }

  const fullTreeWithComp = deepMerge(fullTree, allComponentTokens);
  return resolveAllTokens(merged, fullTreeWithComp);
}

// --- CSS Variables output ---
function generateCSS() {
  let css = '/* AUTO-GENERATED by @c54/tokens — do not edit */\n\n';

  for (const theme of themes) {
    for (const mode of modes) {
      const flat = buildResolved(theme, mode);
      const selector = mode === 'light'
        ? `[data-c54-theme="${theme}"]`
        : `[data-c54-theme="${theme}"][data-c54-mode="dark"]`;

      css += `${selector} {\n`;
      for (const [key, value] of Object.entries(flat)) {
        css += `  --c54-${key}: ${value};\n`;
      }
      css += '}\n\n';
    }
  }

  fs.writeFileSync(path.join(BUILD_DIR, 'css-variables.css'), css);
}

// --- Tailwind config output ---
function generateTailwind() {
  const flat = buildResolved('wire-desk', 'light');

  const colors = {};
  const spacing = {};
  const fontSize = {};
  const borderRadius = {};
  const fontFamily = {};

  for (const [key, value] of Object.entries(flat)) {
    if (key.startsWith('color-')) {
      colors[key] = `var(--c54-${key})`;
    } else if (key.startsWith('space-')) {
      spacing[key] = `var(--c54-${key})`;
    } else if (key.startsWith('font-size-')) {
      fontSize[key.replace('font-size-', '')] = [`var(--c54-${key})`, { lineHeight: '1.5' }];
    } else if (key.startsWith('radius-')) {
      borderRadius[key.replace('radius-', '')] = `var(--c54-${key})`;
    } else if (key.startsWith('font-family-')) {
      fontFamily[key.replace('font-family-', '')] = `var(--c54-${key})`;
    }
  }

  const output = `// AUTO-GENERATED by @c54/tokens — do not edit
export default {
  colors: ${JSON.stringify(colors, null, 2)},
  spacing: ${JSON.stringify(spacing, null, 2)},
  fontSize: ${JSON.stringify(fontSize, null, 2)},
  borderRadius: ${JSON.stringify(borderRadius, null, 2)},
  fontFamily: ${JSON.stringify(fontFamily, null, 2)},
};
`;

  fs.writeFileSync(path.join(BUILD_DIR, 'tailwind-tokens.js'), output);
}

// --- NativeWind / RN output ---
function generateNative() {
  const output = {};

  for (const theme of themes) {
    output[theme] = {};
    for (const mode of modes) {
      output[theme][mode] = buildResolved(theme, mode);
    }
  }

  const js = `// AUTO-GENERATED by @c54/tokens — do not edit
export default ${JSON.stringify(output, null, 2)};
`;

  fs.writeFileSync(path.join(BUILD_DIR, 'nativewind-tokens.js'), js);
}

// --- Index file ---
function generateIndex() {
  const indexJs = `// AUTO-GENERATED by @c54/tokens — do not edit
export { default as tailwindTokens } from './tailwind-tokens.js';
export { default as nativewindTokens } from './nativewind-tokens.js';
export const themes = ${JSON.stringify(themes)};
export const modes = ${JSON.stringify(modes)};
`;

  fs.writeFileSync(path.join(BUILD_DIR, 'index.js'), indexJs);

  const indexDts = `// AUTO-GENERATED by @c54/tokens — do not edit
export declare const tailwindTokens: Record<string, any>;
export declare const nativewindTokens: Record<string, Record<string, Record<string, string>>>;
export declare const themes: readonly string[];
export declare const modes: readonly string[];
`;

  fs.writeFileSync(path.join(BUILD_DIR, 'index.d.ts'), indexDts);
}

console.log('Building @c54/tokens...');
generateCSS();
generateTailwind();
generateNative();
generateIndex();
console.log('Done. Output in ./build/');
